apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: host-pv
  storageClassName: standard
  resources:
    requests:             
      storage: 1Gi
